apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filestash-onlyoffice.fullname" . }}
  labels:
    {{- include "filestash-onlyoffice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.onlyoffice.autoscaling.enabled }}
  replicas: {{ .Values.onlyoffice.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "filestash-onlyoffice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.onlyoffice.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filestash-onlyoffice.labels" . | nindent 8 }}
	{{- with .Values.onlyoffice.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.onlyoffice.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "filestash-onlyoffice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.onlyoffice.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "filestash-onlyoffice.fullname" . }}
          securityContext:
            {{- toYaml .Values.onlyoffice.securityContext | nindent 12 }}
          image: "{{ .Values.onlyoffice.image.repository }}:{{ .Values.onlyoffice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.onlyoffice.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.onlyoffice.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.onlyoffice.resources | nindent 12 }}
          {{- with .Values.onlyoffice.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.onlyoffice.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.onlyoffice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.onlyoffice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.onlyoffice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
